---
- {hosts: all, sudo: yes, roles: [ ansible-role-apt-sources ], tags: [apt_sources] }

- { hosts: all, sudo: yes, roles: [ ansible-locale ], tags: [ locale ] }

- { hosts: all, sudo: yes, roles: [ app_server ], tags: [ app_server ]}