# Generated by Django 3.1.6 on 2021-03-16 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='edgeuser',
            options={'verbose_name': 'user'},
        ),
        migrations.AddField(
            model_name='edgeuser',
            name='name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Full name of user'),
        ),
        migrations.AddField(
            model_name='edgeuser',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pics/', verbose_name='Profile picture'),
        ),
    ]
