# Generated by Django 3.1.6 on 2021-03-19 05:30

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210316_0512'),
    ]

    operations = [
        migrations.AddField(
            model_name='edgeuser',
            name='slug',
            field=models.UUIDField(blank=True, default=uuid.uuid4, editable=False),
        ),
    ]
